CREATE TABLE COURSES (
    COURSEID INT PRIMARY KEY
    COURSERNAME VARCHAR(100),
    DESCRIPTION TEXT, 
    INSTRUCTORID INT, 
    DURATIONHOURS INT, 
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (INSTRUCTORID) REFERENCES INSTRUCTORS01(INSTRUCTORID)
)