CREATE TABLE STUDENTS_COURSES (
    STUDENT_COURSE INT PRIMARY KEY, 
    STUDENTID INT,
    COURSEID INT,
    LOADDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UPDATEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (STUDENTID) REFERENCES STUDENTS01(STUDENTID),
    FOREIGN KEY (COURSEID) REFERENCES COURSERS(COURSEID),
);
